Fix deploy environment

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,4 +1,6 @@
+---
 version: 2.1
+
 orbs:
   slack: circleci/slack@4.10.1
 
@@ -350,7 +352,7 @@ deploy-frontend:
       - revert-migrations
       - notify_on_failure
 
- smoke-test:
+  smoke-test:
     docker:
       - image: cimg/base:2022.04
     steps:
@@ -367,9 +369,9 @@ deploy-frontend:
             export API_URL=http://${BACKEND_IP}:3030
             if curl -s ${API_URL}/api/status | grep "ok"
             then 
-                exit 0
+              exit 0
             else
-                exit 1
+              exit 1
             fi
       - run:
           name: Frontend smoke test.
@@ -386,52 +388,52 @@ deploy-frontend:
       - notify_on_failure
 
   cloudfront-update:
-      docker:
-        - image: cimg/base:stable
-      steps:
-        - checkout
-        - install_awscli
-        - install_nodejs
+    docker:
+      - image: cimg/base:stable
+    steps:
+      - checkout
+      - install_awscli
+      - install_nodejs
 
-        - run:
-            name: Update cloudfront distribution
-            command: |
-              aws cloudformation deploy \
-                --template-file .circleci/files/cloudfront.yml \
-                --parameter-overrides WorkflowID="${CIRCLE_WORKFLOW_ID:0:5}" \
-                --stack-name InitialStack   
-        - destroy-environment
-        - revert-migrations
-        - notify_on_failure 
+      - run:
+          name: Update cloudfront distribution
+          command: |
+            aws cloudformation deploy \
+              --template-file .circleci/files/cloudfront.yml \
+              --parameter-overrides WorkflowID="${CIRCLE_WORKFLOW_ID:0:5}" \
+              --stack-name InitialStack
+      - destroy-environment
+      - revert-migrations
+      - notify_on_failure
 
   cleanup:
-      docker:
-        - image: cimg/base:2022.04 
-      steps:
-        - checkout
-        - install_awscli
-        - attach_workspace:
-            at: ~/
-        - run:
-            name: Get old stack workflow id
-            command: |
-              export OldWorkflowID=$(aws cloudformation \
-                      list-exports --query "Exports[?Name==\`WorkflowID\`].Value" \
-                      --no-paginate --output text)
-              echo OldWorkflowID: "${OldWorkflowID}"
-              echo CIRCLE_WORKFLOW_ID "${CIRCLE_WORKFLOW_ID:0:7}"
-              export STACKS=($(aws cloudformation list-stacks --query "StackSummaries[*].StackName" \
-                      --stack-status-filter CREATE_COMPLETE --no-paginate --output text)) 
-              echo Stack names: "${STACKS[@]}"   
-              if [[ "${CIRCLE_WORKFLOW_ID:0:7}" =~ "${OldWorkflowID}" ]]
-              then
-              echo "-----------------------------DELETE COMPLETE-----------------------------"
-               aws s3 rm "s3://udapeople-${OldWorkflowID}" --recursive
-               aws cloudformation delete-stack --stack-name "udapeople-backend-${OldWorkflowID}"
-               aws cloudformation delete-stack --stack-name "udapeople-frontend-${OldWorkflowID}"
-              else
-              echo "-----------------------------DELETE CANNOT BE PERFORMED-----------------------------"
-              fi
+    docker:
+      - image: cimg/base:2022.04
+    steps:
+      - checkout
+      - install_awscli
+      - attach_workspace:
+          at: ~/
+      - run:
+          name: Get old stack workflow id
+          command: |
+            export OldWorkflowID=$(aws cloudformation \
+                    list-exports --query "Exports[?Name==\`WorkflowID\`].Value" \
+                    --no-paginate --output text)
+            echo OldWorkflowID: "${OldWorkflowID}"
+            echo CIRCLE_WORKFLOW_ID "${CIRCLE_WORKFLOW_ID:0:7}"
+            export STACKS=($(aws cloudformation list-stacks --query "StackSummaries[*].StackName" \
+                    --stack-status-filter CREATE_COMPLETE --no-paginate --output text)) 
+            echo Stack names: "${STACKS[@]}"   
+            if [[ "${CIRCLE_WORKFLOW_ID:0:7}" =~ "${OldWorkflowID}" ]]
+            then
+            echo "-----------------------------DELETE COMPLETE-----------------------------"
+              aws s3 rm "s3://udapeople-${OldWorkflowID}" --recursive
+              aws cloudformation delete-stack --stack-name "udapeople-backend-${OldWorkflowID}"
+              aws cloudformation delete-stack --stack-name "udapeople-frontend-${OldWorkflowID}"
+            else
+            echo "-----------------------------DELETE CANNOT BE PERFORMED-----------------------------"
+            fi
 
 workflows:
   default:
